import type { Metadata } from "next";
import "@repo/ui/globals.css";
import LayoutProvider from "~/components/providers/LayoutProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="relative">
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  );
}
